name: ldc_tool
description: A new Flutter project.
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 自适应分辨率
  flutter_screenutil: ^5.9.3

  # icons
  cupertino_icons: ^1.0.8

  # 下拉刷新
  easy_refresh: ^3.4.0

  # 获取设备信息
  device_info_plus: ^12.3.0

  # 网络请求
  dio: ^5.9.0

  # 状态管理
  get: ^4.7.3

  # 元组支持
  tuple: ^2.0.2

  # 提示框组件
  just_the_tooltip: ^0.0.12

  # 吐司组件
  oktoast: ^3.4.0

  # 评分组件
  flutter_rating_bar: ^4.0.1

  # 日志组件
  logger: ^2.6.2

  # 可见性检测 固定版本0.3.3
  # https://github.com/google/flutter.widgets/issues/295
  # https://github.com/google/flutter.widgets/issues/534
  visibility_detector: 0.3.3

  # # SVG图片支持
  flutter_svg: 2.2.2
  vector_graphics: ^1.1.19

  # 图片加载组件
  extended_image: ^10.0.1

  # Lottie动画支持
  lottie: 3.2.0

  # 轮播组件
  carousel_slider: ^5.1.1
  smooth_page_indicator: 1.2.1

  # 权限管理
  permission_handler: ^12.0.1

  # 滚动视图观察器
  scrollview_observer: ^1.26.2

  # 判断平台
  os_detect: ^2.0.3

  # 应用设置
  app_settings: ^7.0.0

  # 缓存
  hive_ce: ^2.16.0

  # 路径提供
  path_provider: ^2.1.5

  # firebase统计
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6

  # 国际化和本地化功能
  intl: ^0.20.2

dev_dependencies:
  build_runner:
  flutter_gen_runner:

  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false

  fonts:
    enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/common/
    - assets/image/eat/
    - assets/image/eat_list/
    - assets/image/home/
    - assets/json/eat/eat_main.json
    - assets/json/eat/eat_drink.json
    - assets/json/eat/eat_dessert.json
